language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - IP_VERSION=">=2.0,<3.0"
  - IP_VERSION=">=3.0,<4.0"
install:
  - pip install IPython${IP_VERSION}
  - ipython --version
  - pip install -r requirements-dev.txt
  - python setup.py develop
script:
  - python -m flake8 *.py tests/*.py
  - python setup.py test
cache:
  directories:
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
    - /home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
