language: python
sudo: false
python:
  - "3.4"
cache:
  directories:
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
install:
  - "pip install -r requirements-dev.txt"
  - "python setup.py develop"
script: flake8 *.py tests/*.py && python setup.py test
